name = "sharp_beckner_onofri"
version = "0.1.0"
defaultTargets = ["Challenge", "Solution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[lean_lib]]
name = "BecknerOnofri"
globs = ["BecknerOnofri.+"]

[[lean_lib]]
name = "Legacy"
globs = ["Legacy.+"]

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
