import BecknerOnofri.CircleWeightSeries
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals
import Mathlib.MeasureTheory.Integral.DominatedConvergence

/-! The exact improper integral generated by the Poisson-flow remainder.
Termwise Laplace integration gives the same positive-series weight. -/
noncomputable section
open MeasureTheory Set
namespace BecknerOnofri.HighDim.CircleScalar

theorem poisson_weight_integral (n : ℕ) (t : ℝ) (ht : 0≤t) (ht1 : t<1) :
    weight n t=∫ s in Ioi (0:ℝ),
      2*Real.exp (-2*(n+1:ℝ)*s)/(1-t^2*Real.exp (-2*s)) := by
  let μ : Measure ℝ := volume.restrict (Ioi 0)
  let F : ℕ → ℝ → ℝ := fun j s => 2*t^(2*j)*Real.exp ((-2*(n+j+1:ℝ))*s)
  have hneg (j : ℕ) : -2*(n+j+1:ℝ)<0 := by
    have hn := Nat.cast_nonneg (α:=ℝ) n
    have hj := Nat.cast_nonneg (α:=ℝ) j
    linarith
  have hi (j : ℕ) : Integrable (F j) μ :=
    (integrableOn_exp_mul_Ioi (hneg j) 0).const_mul (2*t^(2*j))
  have hint (j : ℕ) : (∫ s,F j s ∂μ)=t^(2*j)/(n+j+1:ℝ) := by
    change (∫ s in Ioi (0:ℝ),2*t^(2*j)*Real.exp ((-2*(n+j+1:ℝ))*s))=_
    rw [integral_const_mul,integral_exp_mul_Ioi (hneg j) 0]
    norm_num only [mul_zero,Real.exp_zero]
    have hd : (n+j+1:ℝ)≠0 := by positivity
    field_simp [hd]
    <;> ring
  have hnorm (j : ℕ) : (∫ s,‖F j s‖ ∂μ)=t^(2*j)/(n+j+1:ℝ) := by
    rw [← hint]
    apply integral_congr_ae
    apply Filter.Eventually.of_forall
    intro s
    change |F j s|=F j s
    apply abs_of_nonneg
    dsimp only [F]
    positivity
  have hsumNorm : Summable (fun j => ∫ s,‖F j s‖ ∂μ) := by
    simp_rw [hnorm]
    exact weight_summable n ht ht1
  have hswap := integral_tsum_of_summable_integral_norm hi hsumNorm
  have hpoint : ∀ᵐ s ∂μ,(∑' j,F j s)=
      2*Real.exp (-2*(n+1:ℝ)*s)/(1-t^2*Real.exp (-2*s)) := by
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with s hs
    have hs0 : 0<s := hs
    have he1 : Real.exp (-2*s)≤1 := Real.exp_le_one_iff.mpr (by linarith [hs0])
    have hz : 0≤t^2*Real.exp (-2*s) := by positivity
    have hz1 : t^2*Real.exp (-2*s)<1 := by
      have he := mul_le_mul_of_nonneg_left he1 (sq_nonneg t)
      nlinarith
    have he (j : ℕ) : Real.exp ((-2*(n+j+1:ℝ))*s)=
        Real.exp (-2*(n+1:ℝ)*s)*Real.exp (-2*s)^j := by
      rw [← Real.exp_nat_mul,← Real.exp_add]
      congr 1
      ring
    have hF (j : ℕ) : F j s=(2*Real.exp (-2*(n+1:ℝ)*s))*(t^2*Real.exp (-2*s))^j := by
      dsimp only [F]
      rw [he,mul_pow,← pow_mul]
      ring
    simp_rw [hF]
    rw [tsum_mul_left,tsum_geometric_of_lt_one hz hz1]
    rfl
  rw [← integral_congr_ae hpoint,← hswap]
  simp_rw [hint]
  rfl

#print axioms poisson_weight_integral
end BecknerOnofri.HighDim.CircleScalar
