import BecknerOnofri.PolarizationL1Properties
import BecknerOnofri.DistributionLimit

/-! Equimeasurability and entropy preservation in the closure of the genuine
finite polarization orbit. Existence and symmetry of a canonical rearranged
limit are separate obligations. -/
noncomputable section
open MeasureTheory ProbabilityTheory Filter Legacy.TorusEndpoint
open scoped Topology
namespace BecknerOnofri.PolarizationL1
open Legacy.BecknerOnofri.CoordinatePolarization

/-- Polarization preserves the full distribution also for merely ae measurable
representatives, not just pointwise measurable functions. -/
theorem polarize_identDistrib {d : ℕ} (i : Fin d) (a : ℝ) {f : Torus d → ℝ}
    (hf : AEStronglyMeasurable f (torusMeasure d)) :
    IdentDistrib (polarize i a f) f (torusMeasure d) (torusMeasure d) := by
  have hp := polarize_aestronglyMeasurable i a hf
  refine ⟨hp.aemeasurable,hf.aemeasurable,?_⟩
  apply ext_of_forall_integral_eq_of_IsFiniteMeasure
  intro φ
  rw [integral_map hp.aemeasurable φ.continuous.aestronglyMeasurable,
    integral_map hf.aemeasurable φ.continuous.aestronglyMeasurable]
  apply polarize_integral_transform i a hf φ.continuous.measurable
  apply (integrable_const ‖φ‖).mono'
    (φ.continuous.measurable.comp_aemeasurable hf.aemeasurable).aestronglyMeasurable
  exact Filter.Eventually.of_forall (fun x => φ.norm_coe_le_norm (f x))

/-- Membership in the actual finite orbit generated by coordinate max/min
polarizations, with arbitrary reflection centers. -/
inductive Orbit {d : ℕ} (f : Torus d → ℝ) : (Torus d → ℝ) → Prop
  | refl : Orbit f f
  | step {g : Torus d → ℝ} : Orbit f g → (i : Fin d) → (a : ℝ) → Orbit f (polarize i a g)

theorem Orbit.identDistrib {d : ℕ} {f g : Torus d → ℝ}
    (h : Orbit f g) (hf : AEStronglyMeasurable f (torusMeasure d)) :
    IdentDistrib g f (torusMeasure d) (torusMeasure d) := by
  induction h with
  | refl => exact IdentDistrib.refl hf.aemeasurable
  | step hg i a ih =>
    exact (polarize_identDistrib i a ih.aestronglyMeasurable_fst).trans ih

/-- Every limit in measure of the finite polarization orbit is equimeasurable
with the original function; this applies, in particular, to L1 limits. -/
theorem orbit_limit_identDistrib {d : ℕ} {f h : Torus d → ℝ}
    (hf : AEStronglyMeasurable f (torusMeasure d)) {g : ℕ → Torus d → ℝ}
    (hg : ∀ n,Orbit f (g n)) (hc : TendstoInMeasure (torusMeasure d) g atTop h) :
    IdentDistrib h f (torusMeasure d) (torusMeasure d) :=
  DistributionLimit.identDistrib_of_tendstoInMeasure (fun n => (hg n).identDistrib hf) hc

/-- Distributional preservation yields equality, rather than only lower
semicontinuity, of the finite entropy in an orbit limit. -/
theorem orbit_limit_entropy {d : ℕ} {f h : Torus d → ℝ}
    (hf : AEStronglyMeasurable f (torusMeasure d)) {g : ℕ → Torus d → ℝ}
    (hg : ∀ n,Orbit f (g n)) (hc : TendstoInMeasure (torusMeasure d) g atTop h)
    (hE : Integrable (fun x => f x*Real.log (f x)) (torusMeasure d)) :
    Integrable (fun x => h x*Real.log (h x)) (torusMeasure d) ∧
    densityEntropy h = densityEntropy f := by
  have he := (orbit_limit_identDistrib hf hg hc).comp Real.continuous_mul_log.measurable
  exact ⟨he.integrable_iff.mpr hE,he.integral_eq⟩

/-- An orbit limit cannot lose nonconstancy. -/
theorem orbit_limit_nonconstant {d : ℕ} {f h : Torus d → ℝ}
    (hf : AEStronglyMeasurable f (torusMeasure d)) {g : ℕ → Torus d → ℝ}
    (hg : ∀ n,Orbit f (g n)) (hc : TendstoInMeasure (torusMeasure d) g atTop h)
    {c : ℝ} (hn : ¬ f=ᵐ[torusMeasure d] (fun _ => c)) :
    ¬ h=ᵐ[torusMeasure d] (fun _ => c) := by
  intro hh
  apply hn
  exact (orbit_limit_identDistrib hf hg hc).ae_snd (measurableSet_singleton c) hh

#print axioms polarize_identDistrib
#print axioms orbit_limit_identDistrib
#print axioms orbit_limit_entropy
#print axioms orbit_limit_nonconstant
end BecknerOnofri.PolarizationL1
