module

public import Legacy.TorusEndpoint.FourierCoefficientCriterion
public import Legacy.TorusEndpoint.FiniteAtomCoefficients

@[expose] public section

/-!
# Instantiating the coefficient criterion with actual finite-atom coefficients

The coefficient family is the complete word sum defined in
`FiniteAtomCoefficients`, not an opaque family satisfying assumed identities.
Only the coefficient cap on nonzero generated frequencies remains a premise.
Polynomial support generation, positivity, and finite convolution domination
are proved here from the actual algebra and complete finite word sums.
-/

open scoped BigOperators
open Legacy.TorusEndpoint.FiniteCone Legacy.TorusEndpoint.FiniteAtomCoefficients

namespace Legacy.TorusEndpoint.FiniteAtomCriterion

/-- Membership in the additive semigroup generated by the finite atoms,
including the empty word and hence zero. -/
def Generated {d : ℕ} (atoms : List (Vec d)) (k : Vec d) : Prop :=
  ∃ xs : List (Vec d), (∀ x ∈ xs, x ∈ atoms) ∧ sumVec xs = k

theorem generated_zero {d : ℕ} (atoms : List (Vec d)) : Generated atoms 0 :=
  ⟨[], by simp, rfl⟩

theorem generated_atom {d : ℕ} (atoms : List (Vec d)) (k : Vec d)
    (hk : k ∈ atoms) : Generated atoms k :=
  ⟨[k], by simpa using hk, sumVec_singleton k⟩

theorem generated_add {d : ℕ} {atoms : List (Vec d)} {i j : Vec d}
    (hi : Generated atoms i) (hj : Generated atoms j) : Generated atoms (i + j) := by
  obtain ⟨xs, hx, hsx⟩ := hi
  obtain ⟨ys, hy, hsy⟩ := hj
  refine ⟨xs ++ ys, ?_, ?_⟩
  · intro x hxys
    rcases List.mem_append.mp hxys with hxx | hxy
    · exact hx x hxx
    · exact hy x hxy
  · rw [sumVec_append, hsx, hsy]
    rfl

/-- A nonzero product coefficient has at least one contributing support pair.
This is proved from the actual algebra coefficient formula. -/
theorem exists_pair_of_mem_product_support {G : Type*} [Add G] [DecidableEq G]
    (F H : AddMonoidAlgebra ℂ G) (k : G) (hk : k ∈ (F * H).coeff.support) :
    ∃ i ∈ F.coeff.support, ∃ j ∈ H.coeff.support, i + j = k := by
  have hn := Finsupp.mem_support_iff.mp hk
  rw [polynomial_coeff_mul, fiberSum] at hn
  obtain ⟨ij, hij, _⟩ := Finset.exists_ne_zero_of_sum_ne_zero hn
  obtain ⟨hp, hs⟩ := Finset.mem_filter.mp hij
  obtain ⟨hi, hj⟩ := Finset.mem_product.mp hp
  exact ⟨ij.1, hi, ij.2, hj, hs⟩

theorem generated_of_mem_affine_support {d : ℕ}
    (atoms : List (Vec d)) (F : AddMonoidAlgebra ℂ (Vec d)) (c : ℂ)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms)
    (k : Vec d) (hk : k ∈ (1 + c • F).coeff.support) : Generated atoms k := by
  classical
  by_cases hk0 : k = 0
  · subst k
    exact generated_zero atoms
  · apply generated_atom atoms k
    apply hF k
    rw [Finsupp.mem_support_iff]
    intro hz
    apply (Finsupp.mem_support_iff.mp hk)
    simp [AddMonoidAlgebra.one_def, hk0, hz]

theorem generated_of_mem_power_support {d : ℕ}
    (atoms : List (Vec d)) (P : AddMonoidAlgebra ℂ (Vec d))
    (hP : ∀ k ∈ P.coeff.support, Generated atoms k)
    (n : ℕ) (k : Vec d) (hk : k ∈ (P ^ n).coeff.support) : Generated atoms k := by
  classical
  induction n generalizing k with
  | zero =>
    have hk0 : k = 0 := by
      simpa [AddMonoidAlgebra.one_def] using hk
    subst k
    exact generated_zero atoms
  | succ n ih =>
    rw [pow_succ] at hk
    obtain ⟨i, hi, j, hj, hsum⟩ := exists_pair_of_mem_product_support (P ^ n) P k hk
    rw [← hsum]
    exact generated_add (ih i hi) (hP j hj)

theorem zero_coefficient_of_atom_support {d : ℕ}
    (atoms : List (Vec d)) (w : Vec d) (F : AddMonoidAlgebra ℂ (Vec d))
    (hw : ∀ k ∈ atoms, 0 < eval w k)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms) : F.coeff 0 = 0 := by
  by_contra hn
  have h := hw 0 (hF 0 (Finsupp.mem_support_iff.mpr hn))
  simp [show (0 : Vec d) = zero from rfl, eval_zero] at h

theorem coefficient_zero_of_not_generated {d : ℕ}
    (atoms : List (Vec d)) (w : Vec d) (a : Vec d → ℝ) (q : ℝ) (k : Vec d)
    (hw : ∀ x ∈ atoms, 0 < eval w x) (hk : ¬ Generated atoms k) :
    coefficient atoms w a q k = 0 := by
  classical
  have he : decompositions atoms w k = ∅ := by
    apply Finset.eq_empty_iff_forall_notMem.mpr
    intro xs hxs
    exact hk ⟨xs, (mem_decompositions_iff atoms w k hw xs).mp hxs⟩
  simp [coefficient, he]

/-- Arbitrary finite support-pair masses are dominated by the true complete
convolution. Frequencies outside its exact finite splitting set contribute
zero; the proof never assumes that arbitrary rectangular supports cover it. -/
theorem coefficient_finite_pair_sum_le {d : ℕ}
    (atoms : List (Vec d)) (w : Vec d) (a : Vec d → ℝ)
    (hw : ∀ x ∈ atoms, 0 < eval w x) (ha : ∀ x ∈ atoms, 0 ≤ a x)
    (p q : ℝ) (hp : 0 ≤ p) (hq : 0 ≤ q)
    (s t : Finset (Vec d)) (k : Vec d) :
    (∑ ij ∈ s ×ˢ t with ij.1 + ij.2 = k,
      coefficient atoms w a p ij.1 * coefficient atoms w a q ij.2) ≤
        coefficient atoms w a (p + q) k := by
  classical
  let pairs := (s ×ˢ t).filter (fun ij ↦ ij.1 + ij.2 = k)
  let lefts := pairs.image Prod.fst
  let term := fun i ↦ coefficient atoms w a p i * coefficient atoms w a q (remainder k i)
  have hrem (ij : Vec d × Vec d) (hij : ij ∈ pairs) : remainder k ij.1 = ij.2 := by
    have hs := (Finset.mem_filter.mp hij).2
    funext l
    have hsl := congrFun hs l
    dsimp [remainder] at *
    omega
  have hinj : Set.InjOn Prod.fst (↑pairs : Set (Vec d × Vec d)) := by
    intro ij hij uv huv he
    apply Prod.ext he
    rw [← hrem ij hij, ← hrem uv huv, he]
  have hsum : (∑ ij ∈ pairs, coefficient atoms w a p ij.1 * coefficient atoms w a q ij.2) =
      ∑ i ∈ lefts, term i := by
    rw [Finset.sum_image hinj]
    apply Finset.sum_congr rfl
    intro ij hij
    simp only [term, hrem ij hij]
  have hnonneg (i : Vec d) : 0 ≤ term i :=
    mul_nonneg (coefficient_nonneg atoms w a i hw ha hp)
      (coefficient_nonneg atoms w a (remainder k i) hw ha hq)
  change (∑ ij ∈ pairs, coefficient atoms w a p ij.1 * coefficient atoms w a q ij.2) ≤ _
  rw [hsum, coefficient_convolution atoms w a p q k hw]
  calc
    ∑ i ∈ lefts, term i ≤ ∑ i ∈ lefts ∪ splitFrequencies atoms w k, term i :=
      Finset.sum_le_sum_of_subset_of_nonneg Finset.subset_union_left
        (fun i _ _ ↦ hnonneg i)
    _ = ∑ i ∈ splitFrequencies atoms w k, term i := by
      symm
      apply Finset.sum_subset Finset.subset_union_right
      intro i _ hi
      exact coefficient_product_zero_outside atoms w a p q k i hw hi

/-- Positivity of the actual coefficient on the support of every actual
affine polynomial power, including the zero-parameter zeroth power. -/
theorem coefficient_pos_on_affine_power_support {d : ℕ}
    (atoms : List (Vec d)) (w : Vec d) (a : Vec d → ℝ)
    (F : AddMonoidAlgebra ℂ (Vec d))
    (hw : ∀ x ∈ atoms, 0 < eval w x) (ha : ∀ x ∈ atoms, 0 < a x)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms)
    (q : ℝ) (hq : 0 < q) (n : ℕ) (k : Vec d)
    (hk : k ∈ ((1 + (q : ℂ) • F) ^ n).coeff.support) :
    0 < coefficient atoms w a ((n : ℝ) * q) k := by
  classical
  cases n with
  | zero =>
    have hk0 : k = 0 := by simpa [AddMonoidAlgebra.one_def] using hk
    subst k
    rw [show (0 : Vec d) = zero from rfl, coefficient_zero atoms w a _ hw]
    norm_num
  | succ n =>
    obtain ⟨xs, hm, hs⟩ := generated_of_mem_power_support atoms (1 + (q : ℂ) • F)
      (generated_of_mem_affine_support atoms F (q : ℂ) hF) (n + 1) k hk
    exact coefficient_pos_of_decomposition atoms w a k hw ha
      (mul_pos (Nat.cast_pos.mpr (Nat.succ_pos n)) hq) xs hm hs

/-- Every field of the previously conditional analytic criterion is now
instantiated by the actual finite-atom coefficient, apart from the stated
cap on nonzero generated frequencies. -/
theorem finite_atom_coefficient_conditions {d : ℕ}
    (atoms : List (Vec d)) (w : Vec d) (a : Vec d → ℝ)
    (F : AddMonoidAlgebra ℂ (Vec d))
    (hw : ∀ x ∈ atoms, 0 < eval w x) (ha : ∀ x ∈ atoms, 0 < a x)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms)
    (hcap : ∀ k, k ≠ 0 → Generated atoms k → coefficient atoms w a 1 k ≤ 1) :
    PolynomialCoefficientConditions F a (coefficient atoms w a) := by
  classical
  refine {
    zero_coefficient := zero_coefficient_of_atom_support atoms w F hw hF
    atom_positive := fun k hk ↦ ha k (hF k hk)
    zero_parameter := coefficient_zero atoms w a 0 hw
    unit_coefficient := fun q _ ↦ coefficient_zero atoms w a q hw
    one_atom := ?_
    power_positive := coefficient_pos_on_affine_power_support atoms w a F hw ha hF
    finite_convolution := ?_
    final_coefficient_cap := ?_ }
  · intro q hq k hk
    exact single_atom_lower_bound atoms w a k hw (fun x hx ↦ (ha x hx).le) hq.le (hF k hk)
  · intro q hq n k _
    simpa only [add_mul, one_mul] using coefficient_finite_pair_sum_le atoms w a hw
      (fun x hx ↦ (ha x hx).le) ((n : ℝ) * q) q
      (mul_nonneg (Nat.cast_nonneg n) hq.le) hq.le
      ((1 + (q : ℂ) • F) ^ n).coeff.support (1 + (q : ℂ) • F).coeff.support k
  · intro k
    by_cases hk0 : k = 0
    · subst k
      rw [show (0 : Vec d) = zero from rfl, coefficient_zero atoms w a 1 hw]
    · by_cases hgen : Generated atoms k
      · exact hcap k hk0 hgen
      · rw [coefficient_zero_of_not_generated atoms w a 1 k hw hgen]
        norm_num

/-- The actual finite-atom coefficient cap implies the Fourier exponential
integral bound, with no residual convolution or support-positivity premise. -/
theorem finite_atom_integral_exp_le {d : ℕ}
    (atoms : List (Frequency d)) (w : Frequency d) (a : Frequency d → ℝ)
    (F : AddMonoidAlgebra ℂ (Frequency d))
    (hw : ∀ x ∈ atoms, 0 < eval w x) (ha : ∀ x ∈ atoms, 0 < a x)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms)
    (hcap : ∀ k, k ≠ 0 → Generated atoms k → coefficient atoms w a 1 k ≤ 1) :
    (∫ x, Real.exp (2 * (polynomialFourierEval d F x).re) ∂torusMeasure d) ≤
      Real.exp (polynomialWeightedL2Sq F a) :=
  fourier_integral_exp_le_of_coefficient_conditions F a (coefficient atoms w a)
    (finite_atom_coefficient_conditions atoms w a F hw ha hF hcap)

/-- The logarithmic conclusion for actual finite Fourier polynomials. -/
theorem finite_atom_log_integral_exp_le {d : ℕ}
    (atoms : List (Frequency d)) (w : Frequency d) (a : Frequency d → ℝ)
    (F : AddMonoidAlgebra ℂ (Frequency d))
    (hw : ∀ x ∈ atoms, 0 < eval w x) (ha : ∀ x ∈ atoms, 0 < a x)
    (hF : ∀ k ∈ F.coeff.support, k ∈ atoms)
    (hcap : ∀ k, k ≠ 0 → Generated atoms k → coefficient atoms w a 1 k ≤ 1) :
    Real.log (∫ x, Real.exp (2 * (polynomialFourierEval d F x).re) ∂torusMeasure d) ≤
      polynomialWeightedL2Sq F a :=
  fourier_log_integral_exp_le_of_coefficient_conditions F a (coefficient atoms w a)
    (finite_atom_coefficient_conditions atoms w a F hw ha hF hcap)

end Legacy.TorusEndpoint.FiniteAtomCriterion
